imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ VirtualtrainingRevisionBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../src/Virtualtraining/RevisionBundle/Resources/public/js/lib/jquery.js'
            filters: [?yui_js]
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js'
            filters: [?yui_js]
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css'
            filters: [cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# Hearsay_Require_js
hearsay_require_js:
  base_dir: %kernel.root_dir%/../src/Virtualtraining/RevisionBundle/Resources/public/js
  #require_js_src: %kernel.root_dir%/../src/Virtualtraining/RevisionBundle/Resources/views/Default/hearsay_requirejs_initialize
  require_js_src: /js/home/lib/require.js
  paths:
    home: @VirtualtrainingRevisionBundle/Resources/public/js
    jquery: @VirtualtrainingRevisionBundle/Resources/public/js/lib/jquery
    backbone: @VirtualtrainingRevisionBundle/Resources/public/js/lib/backbone
    marionette: @VirtualtrainingRevisionBundle/Resources/public/js/lib/backbone.marionette
    underscore: @VirtualtrainingRevisionBundle/Resources/public/js/lib/underscore
    json2: @VirtualtrainingRevisionBundle/Resources/public/js/lib/json2
    bootstrap:  @VirtualtrainingRevisionBundle/Resources/public/js/lib/bootstrap
    handlebars: @VirtualtrainingRevisionBundle/Resources/public/js/lib/handlebars
    app: @VirtualtrainingRevisionBundle/Resources/public/js/app
    stickit: @VirtualtrainingRevisionBundle/Resources/public/js/lib/backbone.stickit
  shim:
      bootstrap:
        deps: [ jquery ]
        exports: bootstrap
      backbone:
        deps: [ underscore, jquery ]
        exports: Backbone
      marionette:
        deps: [ jquery, underscore, backbone, stickit ]
        exports:  Marionette
      underscore:
        exports: _
      handlebars:
        exports: Handlebars
  optimizer:
    #path: %kernel.root_dir%/Resources/public/js/r.js
    path: %kernel.root_dir%/../r.js
    hide_unoptimized_assets:  true
    options:
      name: home/app


fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, html, xml ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API